### ISSUE TITLE
Check box does not work

### ISSUE THREAD

**Issue by Sankalp-eldar** [RishiMatura/ToDoListApp#13]
# Step to reproduce:
1. Mark the task complete.
2. restart the app
3. Completed task is no longer marked

# Expected Behaviour:
Marked task remains marked complete after app restart.

# Additional Feature Request
strick off the task marked completed.

**Comment by RishiMatura** [comment]
@Sankalp-eldar issue resolved kindly open a new issue regarding the strike off feature.
